//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenLover.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAppFunction
    {
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public long AppId { get; set; }
        public string FunctionName { get; set; }
        public Nullable<long> Seq { get; set; }
    }
}
