//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenLover.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRole
    {
        public long Id { get; set; }
        public long CorporationId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
        public Nullable<long> AppId { get; set; }
        public Nullable<long> FunctionId { get; set; }
        public long RoleRelationTypeId { get; set; }
        public string RoleRelationValue { get; set; }
        public long RoleForAllId { get; set; }
        public long AllowRelationTypeId { get; set; }
        public string AllowRelationValue { get; set; }
    }
}
