//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQWebApp_Blank.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class aAppFunction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aAppFunction()
        {
            this.aRoles = new HashSet<aRole>();
            this.aRoleForAlls = new HashSet<aRoleForAll>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public long AppId { get; set; }
        public string FunctionName { get; set; }
        public Nullable<long> Seq { get; set; }
    
        public virtual aApp aApp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aRole> aRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aRoleForAll> aRoleForAlls { get; set; }
    }
}
