//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQWebApp_Blank.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class aRoleForAll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aRoleForAll()
        {
            this.aRoleForSomeAllows = new HashSet<aRoleForSomeAllow>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AppId { get; set; }
        public Nullable<long> FunctionId { get; set; }
        public string RoleName { get; set; }
        public Nullable<long> Seq { get; set; }
    
        public virtual aApp aApp { get; set; }
        public virtual aAppFunction aAppFunction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aRoleForSomeAllow> aRoleForSomeAllows { get; set; }
    }
}
