//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQWebApp_Blank.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class kRelationType
    {
        public long Id { get; set; }
        public long CorporationId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<long> StepRelationTypeId { get; set; }
        public Nullable<long> CompeRelationTypeId { get; set; }
    
        public virtual kRelationTypeForAll kRelationTypeForAll { get; set; }
        public virtual kRelationTypeForAll kRelationTypeForAll1 { get; set; }
    }
}
