//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQWebApp_Blank.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class kReport_History
    {
        public long Id { get; set; }
        public System.DateTime Time { get; set; }
        public long CorporationId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
        public System.Guid UserId { get; set; }
        public long ReportId { get; set; }
        public long StepId { get; set; }
        public long StateId { get; set; }
        public long SendToRelationTypeId { get; set; }
        public string SendToRelationValue { get; set; }
    
        public virtual kRelationTypeForAll kRelationTypeForAll { get; set; }
        public virtual kReport kReport { get; set; }
        public virtual kState kState { get; set; }
        public virtual kStep kStep { get; set; }
    }
}
