//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQWebApp_Blank.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCountry
    {
        public long Id { get; set; }
        public string CountryName { get; set; }
        public Nullable<long> Seq { get; set; }
        public Nullable<long> LanguageId { get; set; }
        public Nullable<long> CurrencyId { get; set; }
    }
}
