//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Function()
        {
            this.GroupUser_Authorize = new HashSet<GroupUser_Authorize>();
            this.User_Dept_Function = new HashSet<User_Dept_Function>();
            this.User_Com_Function = new HashSet<User_Com_Function>();
        }
    
        public int Id { get; set; }
        public int MenuId { get; set; }
        public string Operator { get; set; }
        public string UrlControlAction { get; set; }
        public bool HasExtend { get; set; }
        public Nullable<bool> RequirePermit { get; set; }
    
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupUser_Authorize> GroupUser_Authorize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Dept_Function> User_Dept_Function { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Com_Function> User_Com_Function { get; set; }
    }
}
