//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Cus_PNT
    {
        public int MEM_SEQ { get; set; }
        public string MEM_CARD { get; set; }
        public string MEM_NM { get; set; }
        public string E_MAIL { get; set; }
        public string MEM_ADDR { get; set; }
        public string MOBILE_NO { get; set; }
        public Nullable<int> NO_RECEIP { get; set; }
        public Nullable<int> Sum_PNT { get; set; }
    }
}
