//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailConfig
    {
        public int Id { get; set; }
        public string MailAddress { get; set; }
        public string PassMail { get; set; }
        public string HostMail { get; set; }
        public int PortMail { get; set; }
        public bool SslMail { get; set; }
    }
}
