//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ADMIN_MST
    {
        public string ADMIN_ID { get; set; }
        public string ADMIN_PWD { get; set; }
        public string GRP_ID { get; set; }
        public string ADMIN_NM { get; set; }
        public string DEPT_NM { get; set; }
        public string STAFF_NO { get; set; }
        public string MOBILE_NO { get; set; }
        public string TEL_NO { get; set; }
        public string PWD_CHG_YN { get; set; }
        public string USE_YN { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DT { get; set; }
        public string MOD_ID { get; set; }
        public System.DateTime MOD_DT { get; set; }
    }
}
