//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BRAND_MST
    {
        public string BRD_CD { get; set; }
        public string FLR_CD { get; set; }
        public string DPT_CD { get; set; }
        public string BRAND_CD { get; set; }
        public string BRAND_NM_BackUp { get; set; }
        public string BRAND_NM { get; set; }
        public string SoHopDong { get; set; }
        public string TenGianHang { get; set; }
        public string SoHopDong_Backup { get; set; }
        public string USE_YN { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DT { get; set; }
        public string MOD_ID { get; set; }
        public System.DateTime MOD_DT { get; set; }
    }
}
