//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CD_MST
    {
        public string CD_ID { get; set; }
        public string CD_NM { get; set; }
        public string CD_VAL { get; set; }
        public string UP_CD { get; set; }
        public string CD_DESC { get; set; }
        public Nullable<int> ORD_ORD { get; set; }
        public string USE_YN { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DT { get; set; }
        public string MOD_ID { get; set; }
        public System.DateTime MOD_DT { get; set; }
    }
}
