//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CPAIN_MEM_LIST
    {
        public long LIST_SEQ { get; set; }
        public int CPAIN_SEQ { get; set; }
        public int MEM_SEQ { get; set; }
    }
}
