//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CPAIN_MST
    {
        public int CPAIN_SEQ { get; set; }
        public string CPAIN_SUBJ { get; set; }
        public string APY_S_DAY { get; set; }
        public string APY_E_DAY { get; set; }
        public Nullable<int> TGET_CNT { get; set; }
        public string CPAIN_DESC { get; set; }
        public string USE_YN { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DT { get; set; }
        public string MOD_ID { get; set; }
        public System.DateTime MOD_DT { get; set; }
    }
}
