//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DAY_CLOSE_BY_LINE
    {
        public string BRD_CD { get; set; }
        public string CLOSE_DAY { get; set; }
        public string LIN_CD { get; set; }
        public Nullable<int> SALE_CNT_SUM { get; set; }
        public Nullable<long> PAY_SUM { get; set; }
        public Nullable<int> DISC_SUM { get; set; }
        public Nullable<long> CARD_PAY_SUM { get; set; }
        public Nullable<long> CASH_PAY_SUM { get; set; }
        public Nullable<long> GIFT_PAY_SUM { get; set; }
        public Nullable<long> PNT_PAY_SUM { get; set; }
        public Nullable<long> ETC_PAY_SUM { get; set; }
        public Nullable<long> ADD_PNT_SUM { get; set; }
        public Nullable<int> NML_CNT { get; set; }
        public Nullable<int> RTN_CNT { get; set; }
        public Nullable<int> CNCL_CNT { get; set; }
        public Nullable<int> MEM_SALE_CNT_SUM { get; set; }
        public Nullable<long> MEM_PAY_SUM { get; set; }
        public Nullable<int> MEM_DISC_SUM { get; set; }
        public Nullable<long> MEM_CARD_PAY_SUM { get; set; }
        public Nullable<long> MEM_CASH_PAY_SUM { get; set; }
        public Nullable<long> MEM_GIFT_PAY_SUM { get; set; }
        public Nullable<long> MEM_PNT_PAY_SUM { get; set; }
        public Nullable<long> MEM_ETC_PAY_SUM { get; set; }
        public Nullable<long> MEM_ADD_PNT_SUM { get; set; }
        public Nullable<int> MEM_NML_CNT { get; set; }
        public Nullable<int> MEM_RTN_CNT { get; set; }
        public Nullable<int> MEM_CNCL_CNT { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DT { get; set; }
        public string MOD_ID { get; set; }
        public System.DateTime MOD_DT { get; set; }
    }
}
