//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ERR_TBL
    {
        public long ERR_SEQ { get; set; }
        public string ERR_TGET { get; set; }
        public string ERR_CD { get; set; }
        public string ERR_FG { get; set; }
        public string ERR_CONT { get; set; }
        public string ERR_PROC { get; set; }
        public string ERR_LINE { get; set; }
        public string ERR_NUM { get; set; }
        public string ERR_STA { get; set; }
        public string ERR_MSG { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DT { get; set; }
        public string MOD_ID { get; set; }
        public System.DateTime MOD_DT { get; set; }
    }
}
