//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HOBI_INFO
    {
        public int HOBI_SEQ { get; set; }
        public int MEM_SEQ { get; set; }
        public string HOBI_CD { get; set; }
        public string ETC_HOBI { get; set; }
    }
}
