//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JOIN_LOG
    {
        public long LOG_SEQ { get; set; }
        public string ADMIN_ID { get; set; }
        public string MENU_ID { get; set; }
        public System.DateTime JOIN_DT { get; set; }
    }
}
