//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MEM_MST
    {
        public int MEM_SEQ { get; set; }
        public string MEM_CARD { get; set; }
        public string MEM_NM { get; set; }
        public string GRADE_CD { get; set; }
        public string NAT_CD { get; set; }
        public string CERTI_NO { get; set; }
        public string MEM_BIRTHDAY { get; set; }
        public string AGE_CD { get; set; }
        public string SEX_CD { get; set; }
        public string MAJOR_AREA { get; set; }
        public string MINOR_AREA { get; set; }
        public string MEM_ADDR { get; set; }
        public string TEL_NO { get; set; }
        public string MOBILE_NO { get; set; }
        public string E_MAIL { get; set; }
        public string COMPY_NM { get; set; }
        public string COMPY_POS { get; set; }
        public string COMPY_ADDR { get; set; }
        public string COMPY_TEL_NO { get; set; }
        public string JOB_CD { get; set; }
        public string WEDDING_CD { get; set; }
        public string WEDDING_DAY { get; set; }
        public Nullable<byte> CHILD_CNT { get; set; }
        public string CAR_YN { get; set; }
        public string AUTOBY_YN { get; set; }
        public string INCOME_CD { get; set; }
        public string USE_YN { get; set; }
        public Nullable<System.DateTime> LEAVE_DT { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DT { get; set; }
        public string MOD_ID { get; set; }
        public System.DateTime MOD_DT { get; set; }
        public string Mem_Card_Old { get; set; }
        public string Mem_Card_Edit_At { get; set; }
        public string Mem_Card_Edit_By { get; set; }
        public string Mem_Card_Edit_Time { get; set; }
        public Nullable<bool> Invalid_Card_Number { get; set; }
    }
}
