//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MEM_MST_Backup
    {
        public int MEM_SEQ { get; set; }
        public string MEM_CARD { get; set; }
        public string MEM_NM { get; set; }
        public string MOBILE_NO_Backup { get; set; }
        public string MOBILE_NO_New { get; set; }
        public int MOBILE_NO_Edited { get; set; }
    }
}
