//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PNT_HIS_INFO
    {
        public long PNT_HIS_SEQ { get; set; }
        public Nullable<int> MEM_SEQ { get; set; }
        public Nullable<int> CHG_PNT { get; set; }
        public Nullable<long> CHG_PNT_Edit { get; set; }
        public string Edit_At { get; set; }
        public string Edit_By { get; set; }
        public string Edit_Time { get; set; }
        public string CHG_RSN_CD { get; set; }
        public string PNT_RSN { get; set; }
        public string PNT_RSN_Backup { get; set; }
        public Nullable<long> SALE_SEQ { get; set; }
        public string REG_ID { get; set; }
        public Nullable<System.DateTime> REG_DT { get; set; }
        public string MOD_ID { get; set; }
        public Nullable<System.DateTime> MOD_DT { get; set; }
        public Nullable<bool> Is_Manual_Add_Point { get; set; }
        public string Add_By_Group { get; set; }
        public string Add_At { get; set; }
        public Nullable<long> Mem_SEQ_Old { get; set; }
        public string Mem_SEQ_Edit_At { get; set; }
        public string Mem_SEQ_Edit_By { get; set; }
        public string Mem_SEQ_Edit_Time { get; set; }
    }
}
