//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PNT_MST
    {
        public int PNT_SEQ { get; set; }
        public string PNT_FG { get; set; }
        public string PNT_SUBJ { get; set; }
        public string APY_S_DAY { get; set; }
        public string APY_E_DAY { get; set; }
        public Nullable<int> GRADE_1_BY_AMT { get; set; }
        public Nullable<decimal> GRADE_1_PNT { get; set; }
        public Nullable<decimal> GRADE_1_ADD { get; set; }
        public Nullable<int> GRADE_2_BY_AMT { get; set; }
        public Nullable<decimal> GRADE_2_PNT { get; set; }
        public Nullable<decimal> GRADE_2_ADD { get; set; }
        public Nullable<int> GRADE_3_BY_AMT { get; set; }
        public Nullable<decimal> GRADE_3_PNT { get; set; }
        public Nullable<decimal> GRADE_3_ADD { get; set; }
        public string PNT_DESC { get; set; }
        public Nullable<int> PNT_PAY { get; set; }
        public string USE_YN { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DT { get; set; }
        public string MOD_ID { get; set; }
        public System.DateTime MOD_DT { get; set; }
    }
}
