//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REQ_DT_INFO
    {
        public long REQ_DT_SEQ { get; set; }
        public Nullable<long> REQ_SEQ { get; set; }
        public string ITEM_BCD { get; set; }
        public string BRD_CD { get; set; }
        public string LIN_CD { get; set; }
        public Nullable<int> SALE_CNT { get; set; }
        public Nullable<long> SALE_AMT { get; set; }
        public Nullable<int> DISC_AMT { get; set; }
        public Nullable<long> PAY_AMT { get; set; }
        public Nullable<int> ADD_PNT { get; set; }
    }
}
