//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SALE_INFO
    {
        public long SALE_SEQ { get; set; }
        public string SALE_FG { get; set; }
        public string MEM_YN { get; set; }
        public Nullable<int> MEM_SEQ { get; set; }
        public string MEM_CARD { get; set; }
        public string RECP_NO { get; set; }
        public string BRD_CD { get; set; }
        public string BIZ_DAY { get; set; }
        public Nullable<System.DateTime> SALE_DT { get; set; }
        public Nullable<long> PAY_AMT { get; set; }
        public Nullable<int> DISC_AMT { get; set; }
        public Nullable<long> CARD_PAY_AMT { get; set; }
        public Nullable<long> CASH_PAY_AMT { get; set; }
        public Nullable<long> GIFT_PAY_AMT { get; set; }
        public Nullable<long> PNT_PAY_AMT { get; set; }
        public Nullable<long> ETC_PAY_AMT { get; set; }
        public Nullable<int> ADD_PNT { get; set; }
        public Nullable<int> USE_PNT { get; set; }
        public string CNCL_YN { get; set; }
        public string CNCL_BIZ_DAY { get; set; }
        public Nullable<System.DateTime> CNCL_DT { get; set; }
        public string POS_NO { get; set; }
        public string CNCL_POS_NO { get; set; }
        public string CASHER_NO { get; set; }
        public string ORG_RECP_NO { get; set; }
        public string RTN_REQ_SEQ { get; set; }
        public string RTN_MEM_NM { get; set; }
        public string RTN_MEM_TELNO { get; set; }
        public string CLOSE_YN { get; set; }
        public string CLOSE_DAY { get; set; }
        public string CNCL_CLOSE_YN { get; set; }
        public string CNCL_CLOSE_DAY { get; set; }
        public string REG_ID { get; set; }
        public System.DateTime REG_DT { get; set; }
        public string MOD_ID { get; set; }
        public System.DateTime MOD_DT { get; set; }
        public Nullable<bool> Is_Manual_Add_Point { get; set; }
        public string MaThue { get; set; }
        public Nullable<long> ADD_PNT_Edit { get; set; }
        public string Edit_At { get; set; }
        public string Edit_By { get; set; }
        public string Edit_Time { get; set; }
        public Nullable<long> Mem_SEQ_Old { get; set; }
        public string Mem_SEQ_Edit_At { get; set; }
        public string Mem_SEQ_Edit_By { get; set; }
        public string Mem_SEQ_Edit_Time { get; set; }
        public string RECP_NO_Old { get; set; }
    }
}
