//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.User_Com_Function = new HashSet<User_Com_Function>();
            this.User_Dept_Function = new HashSet<User_Dept_Function>();
            this.GroupUsers = new HashSet<GroupUser>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> TitleId { get; set; }
        public string FullName { get; set; }
        public string FullNameEn { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string BitexcoPhoneExt { get; set; }
        public byte[] ImageSignature { get; set; }
        public string SignImageType { get; set; }
        public bool Active { get; set; }
        public bool IsLock { get; set; }
        public Nullable<bool> ConfirmCheck { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public string UserPass { get; set; }
        public Nullable<int> AdministratorshipID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Extension { get; set; }
        public Nullable<byte> RemindAdminFlg { get; set; }
        public Nullable<System.DateTime> StartWorkingDate { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> NumberOfDaysLeave { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Com_Function> User_Com_Function { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Dept_Function> User_Dept_Function { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupUser> GroupUsers { get; set; }
    }
}
