//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace BtcKpi.Model
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Ipf
    {
		[Key]
        public int ID { get; set; }
        public Nullable<byte> PersonType { get; set; }
        public Nullable<byte> ScheduleType { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<byte> DeleteFlg { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<decimal> WorkScore { get; set; }
        public Nullable<decimal> CompetencyScore { get; set; }
        public Nullable<decimal> TotalScore { get; set; }
        public string SelfComment { get; set; }
        public string ManagerComment { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public Nullable<int> ApproveBy { get; set; }
        [NotMapped]
        public string ScheduleName { get; set; }
        public Nullable<int> BodId { get; set; }
        public Nullable<decimal> BodScore { get; set; }
        public string BodComment { get; set; }
    }
}
