//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace BtcKpi.Model
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PerformanceLSFB
    {
		[Key]
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> TypePerformanceId { get; set; }
        public Nullable<int> QuarterId { get; set; }
        public Nullable<byte> OfficeArea { get; set; }
        public Nullable<byte> OfficeMonthMoney { get; set; }
        public Nullable<byte> OfficeTY { get; set; }
        public Nullable<byte> OfficeLY { get; set; }
        public Nullable<byte> RetailArea { get; set; }
        public Nullable<byte> RetailMonthMoney { get; set; }
        public Nullable<byte> RetailTY { get; set; }
        public Nullable<byte> RetailLY { get; set; }
        public Nullable<byte> NewArea { get; set; }
        [NotMapped]
        public Nullable<byte> NewAreaLS68BFT { get; set; }
        [NotMapped]
        public Nullable<byte> NewMonthMoneyLS68BFT { get; set; }
        [NotMapped]
        public Nullable<byte> NewTotalRevLS68BFT { get; set; }
        public Nullable<byte> NewMonthMoney { get; set; }
        public Nullable<byte> NewTotalRev { get; set; }
        public Nullable<byte> TotalMonthMoney { get; set; }
        public Nullable<byte> TotalRevTY { get; set; }
        public Nullable<byte> TotalRevLY { get; set; }
        public Nullable<byte> TotalGrossTY { get; set; }
        public Nullable<byte> TotalGrossLY { get; set; }
        public Nullable<int> TypeFB { get; set; }
        [NotMapped]
        public Nullable<int> TypeFBLS { get; set; }
        [NotMapped]
        public Nullable<int> TypeFBBFT { get; set; }
        public Nullable<byte> SalesLineToLine { get; set; }
        [NotMapped]
        public Nullable<byte> SalesLineToLineLS { get; set; }
        [NotMapped]
        public Nullable<byte> SalesLineToLineBFT { get; set; }
        public Nullable<byte> SalesAll { get; set; }
        [NotMapped]
        public Nullable<byte> SalesAllLS { get; set; }
        [NotMapped]
        public Nullable<byte> SalesAllBFT { get; set; }
        public Nullable<byte> SalesCashFlowTY { get; set; }
        [NotMapped]
        public Nullable<byte> SalesCashFlowTYLS { get; set; }
        [NotMapped]
        public Nullable<byte> SalesCashFlowBFT { get; set; }
        public Nullable<byte> SalesCashFlowLY { get; set; }
        [NotMapped]
        public Nullable<byte> SalesCashFlowLYLS { get; set; }
        public Nullable<byte> RevLineTOSNoMG { get; set; }
        [NotMapped]
        public Nullable<byte> RevLineTOSNoMGBFT { get; set; }
        [NotMapped]
        public Nullable<byte> RevLineTOSWithMGBFT { get; set; }
        public Nullable<byte> RevLineTOSWithMG { get; set; }
        public Nullable<byte> RevLineNoMG { get; set; }
        [NotMapped]
        public Nullable<byte> RevLineNoMGBFT { get; set; }
        [NotMapped]
        public Nullable<byte> RevLineWithMGBFT { get; set; }
        public Nullable<byte> RevLineWithMG { get; set; }
        public Nullable<byte> RevAllTOSNoMG { get; set; }
        [NotMapped]
        public Nullable<byte> RevAllTOSNoMGBFT { get; set; }
        [NotMapped]
        public Nullable<byte> RevAllTOSWithMGBFT { get; set; }
        [NotMapped]
        public Nullable<byte> RevAllNoMGBFT { get; set; }
        [NotMapped]
        public Nullable<byte> RevAllWithMGBFT { get; set; }
        public Nullable<byte> RevAllTOSWithMG { get; set; }
        public Nullable<byte> RevAllNoMG { get; set; }
        public Nullable<byte> RevAllWithMG { get; set; }
        public Nullable<byte> RevAllLY { get; set; }
        public Nullable<byte> RevAllOPMonthMoney { get; set; }
        public Nullable<byte> RevTotalNoMG { get; set; }
        [NotMapped]
        public Nullable<byte> RevTotalNoMGLS { get; set; }
        [NotMapped]
        public Nullable<byte> RevTotalNoMGBFT { get; set; }
        [NotMapped]
        public Nullable<byte> RevTotalWithMGBFT { get; set; }
        public Nullable<byte> RevTotalWithMG { get; set; }
        public Nullable<byte> RevTotalMonthMoney { get; set; }
        [NotMapped]
        public Nullable<byte> RevTotalWithMGLS { get; set; }
        [NotMapped]
        public Nullable<byte> RevTotalMonthMoneyBFT { get; set; }
        public Nullable<byte> RevTotalLY { get; set; }
        [NotMapped]
        public Nullable<byte> RevTotalLYLS { get; set; }
        public Nullable<byte> ComProfitTY { get; set; }
        [NotMapped]
        public Nullable<byte> ComProfitTYLS { get; set; }
        public Nullable<byte> ComProfitLY { get; set; }
        [NotMapped]
        public Nullable<byte> ComProfitLYLS { get; set; }
        [NotMapped]
        public Nullable<byte> RevLSAreaLS68BFT { get; set; }
        [NotMapped]
        public Nullable<byte> RevLSMonthMoneyLS68BFT { get; set; }
        [NotMapped]
        public Nullable<byte> RevTotalMonthMoneyLS68BFT { get; set; }
        [NotMapped]
        public Nullable<byte> RevTotalNoMGLS68BFT { get; set; }
        public Nullable<byte> RevLSArea { get; set; }
        public Nullable<byte> RevLSMonthMoney { get; set; }
        public Nullable<byte> RevLSRev { get; set; }
        public Nullable<byte> RevLSOPMonthMoney { get; set; }
        public Nullable<byte> BusinessProfit { get; set; }
        [NotMapped]
        public Nullable<byte> BusinessProfitBFT { get; set; }
        [NotMapped]
        public Nullable<byte> ComProfitTYBFT { get; set; }
        public Nullable<byte> RevAllOccRate { get; set; }
        public Nullable<byte> RevNormalLine { get; set; }
        public Nullable<byte> RevNormalAll { get; set; }
        public Nullable<byte> RevAllRev { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<byte> DeleteFlg { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Comment { get; set; }
        [NotMapped]
        public bool CheckExistsPerformance { get; set; }
        [NotMapped]
        public int ShowFormByProjType { get; set; }
        [NotMapped]
        public Nullable<byte> RevTotalWithMGLS68BFT { get; set; }
        [NotMapped]
        public Nullable<byte> BusinessProfitLS68BFT { get; set; }
        [NotMapped]
        public Nullable<byte> ComProfitTYLS68BFT { get; set; }
        [NotMapped]
        public Nullable<byte> RevHelipadLS68BFT { get; set; }
        public Nullable<byte> RevHelipad { get; set; }
        [NotMapped]
        public Nullable<byte> RevEventLS68BFT { get; set; }
        public Nullable<byte> RevEvent { get; set; }
        [NotMapped]
        public Nullable<byte> RevChicilonLS68BFT { get; set; }
        public Nullable<byte> RevChicilon { get; set; }
        [NotMapped]
        public Nullable<byte> RevATMLS68BFT { get; set; }
        public Nullable<byte> RevATM { get; set; }
        [NotMapped]
        public Nullable<byte> RevSignageLS68BFT { get; set; }
        public Nullable<byte> RevSignage { get; set; }
        [NotMapped]
        public Nullable<byte> RevTotalLS68BFT { get; set; }
        public Nullable<byte> RevTotal { get; set; }
        [NotMapped]
        public Nullable<byte> RevTotalPMG68BFT { get; set; }
        public Nullable<byte> RevTotalPMG { get; set; }
        [NotMapped]
        public Nullable<byte> BusinessProfitLS68BFTCL { get; set; }
        [NotMapped]
        public Nullable<byte> ComProfitTYLS68BFTCL { get; set; }
        [NotMapped]
        public Nullable<byte> NewAreaBFTLS { get; set; }
        [NotMapped]
        public Nullable<byte> NewMonthMoneyBFTLS { get; set; }
        [NotMapped]
        public Nullable<byte> NewTotalRevBFTLS { get; set; }
        [NotMapped]
        public Nullable<byte> RetailAreaBFTLS { get; set; }
        [NotMapped]
        public Nullable<byte> RetailMonthMoneyBFTLS { get; set; }
        [NotMapped]
        public Nullable<byte> RetailTYBFTLS { get; set; }
        [NotMapped]
        public Nullable<byte> RevLineToLineBFTLS { get; set; }
        [NotMapped]
        public Nullable<byte> RevAllBFTLS { get; set; }
        [NotMapped]
        public Nullable<byte> TotalMonthMoneyBFTLS { get; set; }
        [NotMapped]
        public Nullable<byte> RevLSRevBFTLS { get; set; }
        [NotMapped]
        public Nullable<byte> BusinessProfitLSBFTCL { get; set; }
        [NotMapped]
        public Nullable<byte> ComProfitTYLSBFTCL { get; set; }
        public Nullable<byte> SkyAdults { get; set; }
        public Nullable<byte> SkyChildrenSenior { get; set; }
        public Nullable<byte> SkyTravelAgent { get; set; }
        public Nullable<byte> TWOHVisitors { get; set; }
        public Nullable<byte> TWOHTravelAgent { get; set; }
        public Nullable<byte> MotoFixed { get; set; }
        public Nullable<byte> MotoOutside { get; set; }
        public Nullable<byte> CarFixed { get; set; }
        public Nullable<byte> CarOutside { get; set; }
        public Nullable<byte> RevMotoFixed { get; set; }
        public Nullable<byte> RevMotoOutside { get; set; }
        public Nullable<byte> RevCarFixed { get; set; }
        public Nullable<byte> RevCarOutside { get; set; }
        public Nullable<byte> RevTotalParking { get; set; }
        [NotMapped]
        public Nullable<byte> BusinessProfitParking { get; set; }
        [NotMapped]
        public Nullable<byte> ComProfitParking { get; set; }

    }
}
