//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtcKpi.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RolesFunction
    {
        [Key]
        public int ID { get; set; }
        public Nullable<byte> CanView { get; set; }
        public Nullable<byte> CanAdd { get; set; }
        public Nullable<byte> CanEdit { get; set; }
        public Nullable<byte> CanDelete { get; set; }
        public Nullable<byte> CanComment { get; set; }
        public Nullable<byte> CanApprove { get; set; }
        public Nullable<byte> FullFlg { get; set; }
        public int RoleID { get; set; }
        public int FunctionID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<byte> DeleteFlg { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    }
}
