//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtcKpi.Model
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UpfCross
    {
		[Key]
        public int ID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<byte> DependWeight { get; set; }
        public Nullable<decimal> DependScore { get; set; }
        public Nullable<byte> SelfWeight { get; set; }
        public Nullable<decimal> SelfScore { get; set; }
        public Nullable<decimal> TotalScore { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<byte> DeleteFlg { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    }
}
