//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtcKpi.Model
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UpfCrossDetail
    {
		[Key]
        public int ID { get; set; }
        public int UpfCrossID { get; set; }
        public string Objective { get; set; }
        public Nullable<int> FromDepartment { get; set; }
        public string ContentsRequested { get; set; }
        public string ExpectedTimeOfCompletion { get; set; }
        public string ExpectedResult { get; set; }
        public Nullable<byte> FromWeight { get; set; }
        public Nullable<int> ToDepartment { get; set; }
        public string TimeOfCompletion { get; set; }
        public string Result { get; set; }
        public Nullable<decimal> FromScore { get; set; }
        public string PlanToDo { get; set; }
        public string ExplainationForResults { get; set; }
        public string Solutions { get; set; }
        public string Timeline { get; set; }
        public Nullable<byte> ToWeight { get; set; }
        public Nullable<decimal> ToScore { get; set; }
        public string AssessmentByCouncil { get; set; }
        public Nullable<decimal> TotalScore { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<byte> DeleteFlg { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    }
}
