//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Event.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterEvent
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Họ tên bắt buộc nhập!")]
        [Display(Name = "Họ tên")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Số điện thoại bắt buộc nhập!")]
        [Display(Name = "Số điện thoại")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^(03|05|07|08|09)(\d{8})$", ErrorMessage = "Số điện thoại không hợp lệ!")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Email bắt buộc nhập!")]
        [EmailAddress(ErrorMessage = "Email không hợp lệ!")]
        //[DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        //[RegularExpression(@"^[a-zA-Z0-9._%+-]+(@gmail\.com|@yahoo\.com|@hotmail\.com|@outlook\.com|@bitexco\.com\.vn|@bigcapital\.com\.vn|@bitexcojsc\.com\.vn|@yandex\.com|@yahoo\.com.vn|@yahoo\.co\.uk)$", ErrorMessage = "Email không hợp lệ!")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Mã vòng bắt buộc nhập!")]
        [Display(Name = "Mã vòng")]
        public string RoundNumber { get; set; }
        public Nullable<System.DateTime> CreateDated { get; set; }
        public string Win { get; set; }

        [NotMapped]
        public string CompleteDateString
        {
            get { return Convert.ToDateTime(CreateDated).ToString("dd/MM/yyyy"); }
            set { CompleteDateString = value; }
        }
        public string Description { get; set; }
        [NotMapped]
        public string WinString
        {
            get { return Win == "1" ? "Trúng thưởng" : ""; }
            set { WinString = value; }
        }
    }
}
